### ISSUE TITLE
Launching server using command svls failed

### ISSUE THREAD

**Issue by DeeeeLAN** [dalance/svls-vscode#1]
I have svls installed in the system PATH, I can run the command just fine from a terminal. When I open VSCode and an SV file, this is the output I get in the output window:

```
[Error - 11:47:24 AM] Starting client failed
Launching server using command svls failed.
```

**Comment by dalance** [comment]
Thank you for your report.
I want to reproduce the issue.
Could you explain your environment?

**Comment by DeeeeLAN** [comment]
Linux, latest VSCode, I downloaded the binary from the release page and put it in the path. I can access it from the command prompt. Anything specific you need to know? Are there any additional dependencies needed?

**Comment by dalance** [comment]
The released binary for Linux is static linked and no dependencies is needed.
Could you execute with `--version` from the command prompt?

```
$ svls --version
svls "0.1.13 ( rev: b1df1a9, rustc: 1.41.0, build at: 2020/02/09 13:43:24 )"
```

**Comment by DeeeeLAN** [comment]
```
> svls --version
svls "0.1.13 ( rev: b1df1a9, rustc: 1.41.0, build at: 2020/02/09 13:43:24 )"
```

**Comment by DeeeeLAN** [comment]
It looks like my vscode launcher wasn’t using the right environment. Launching from a shell that could find svls worked.
