### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by supleed2** [dalance/svls-vscode#11]
There doesn't seem to be a contributions.md or guide so I thought I'd make an issue. I have tried making changes to add 3 features and I just finished splitting them into 3 branches that can be merged in individually:

- [Syntax Highlighting](https://github.com/supleed2/svls-vscode/tree/supleed2_syntax_highlighting), as requested in #6
  - Uses the `tmLanguage` from the linked repository and one more, referenced in the commit
- [Snippets](https://github.com/supleed2/svls-vscode/tree/supleed2_snippets)
  - I thought it was helpful and I made some changes to add a few variants, mainly around having/not having `begin` and `end`
- [Configuration](https://github.com/supleed2/svls-vscode/tree/supleed2_svlint_config)
  - I wanted to be able to set the config.toml used by svlint more easily without needing to copy it into each project, but it leaves the default behaviour intact.

I haven't changed the `CHANGELOG.md` or `version` in `package.json` as the changes I made are split across branches and I wasn't sure how to format the changelog.

**Comment by dalance** [comment]
Thank you for your contribution!
I want to merge all PRs, but I have a concern about license.
How about copyright notice of based repositories?

**Comment by dalance** [comment]
> Since it is based on code under the MIT license, and this repo is also under MIT, would a comment within the relevant files outlining the copyright holders be the right way?

I think that's right.

**Comment by supleed2** [comment]
Could a new release also be added to the VSCode Marketplace? Thanks for your help!

**Comment by dalance** [comment]
I released v0.0.2.
