### ISSUE TITLE
Couldn't start client SystemVerilog language server

### ISSUE THREAD

**Issue by jainamq** [dalance/svls-vscode#2]
I am using svls for windows x64 machine. I did download svls extension and installed, and updated the path variable also.

**Comment by dalance** [comment]
Could you execute the following command from Command Prompt?

```
$ svls --version
```

**Comment by jainamq** [comment]
Hello Dalance,
C:\Users\jainams>svls --version
svls "0.1.16 ( rev: c227ee1, rustc: 1.42.0, build at: 2020/04/03 09:30:21 )"

Regards
Jainam

**Comment by dalance** [comment]
Is there any message at "Output" of "SystemVerilog language server" window?
The following is the expected message.

![image](https://user-images.githubusercontent.com/4331004/78634662-670a7480-78df-11ea-93ad-b62cf5703af2.png)

**Comment by jainamq** [comment]
Hello dalance,
the issue is fixed after I restarted the laptop. I am sure the path variable was updated before the restart since i was able to run the svls cmd in the cmd prompt. 

Issue is fixed after the restarting the laptop.

Regards
Jainam

**Comment by dalance** [comment]
OK.
The variable update may not be affected to VSCode before reboot.
